env:
  browser: true
  es2021: true
extends:
  - google
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - "@typescript-eslint"
rules: { "indent": ["error", 4], object-curly-spacing: ["error", "always"] }
